//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterData
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CharacterName { get; set; }
        public string CharacterClassName { get; set; }
        public string CharacterLastLocationName { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
